#### Перехват ошибок — `try...catch`

Пример валидации пользовательского ввода с помощью конструкции `try...catch`.

```js
// Получаем введенное значение
let x = document.getElementById('myNum').value;

try {
  // Тестируемый блок кода.
  if(x == '') throw 'is empty';
  if(isNaN(x)) throw 'not a number';
  if(x > 10) throw 'too high';
  if(x < 5) throw 'too low';
} catch(err) {
  // Обработчик ошибки
  message.innerHTML = 'Input ' + err;
} finally {
  // Необязательный раздел завершения проверки.
  console.log('');
}
```

Инструкция `throw` позволяет создавать пользовательские сообщения об ошибках (генерировать исключения в профессиональных терминах). Выполнение текущей функции будет остановлено (инструкции после `throw` не будут выполнены), и управление будет передано в ближайший блок `catch`. Если `catch` ниже нет, выполнение программы будет остановлено. [Подробнее](https://www.w3schools.com/js/js_errors.asp){:target="_blank"}.

Необязательный раздел `finally` выполняется в любом случае:

- после `try`, если не было ошибок,
- после `catch`, если ошибки были.

#### Стандартные ошибки

В JavaScript встроен ряд конструкторов для обработки стандартных ошибок.

- `RangeError` — значение не входит в множество или выходит за диапазон допустимых значений.
- `ReferenceError` — ошибка, возникающая при обращении к несуществующей переменной.
- `SyntaxError` — синтаксически неправильный код.
- `TypeError` — ошибка, связанная с типом данных.
- `URIError` — ошибка декодирования или кодирования URI.

```js
// В объекте нет имени пользователя
const data = '{ "age": 30 }';

try {
  // выполнится без ошибок
  const user = JSON.parse(data);

  if (!user.name) {
    /* Для вывода ошибки используется стандартный
    конструктор */
    throw new SyntaxError('Данные некорректны');
  }

  alert(user.name);
} catch (err) {
  alert('Извините, в данных ошибка');
}
```
